### ISSUE TITLE
Date and time not displayed when viewing event details

### ISSUE THREAD

**Issue by kerijacoby** [sugarcalendar/lite#22]
**Steps to replicate:**
Create a new event with a specified date, time, location, and details.
Save the event to the calendar of your choice.
<img width="1536" alt="Screen Shot 2019-10-11 at 9 59 53 AM" src="https://user-images.githubusercontent.com/30249621/66662165-ec052180-ec0d-11e9-8c01-9573f1b4cae9.png">
View the event. The date and time are not displayed.
<img width="347" alt="Screen Shot 2019-10-11 at 10 04 07 AM" src="https://user-images.githubusercontent.com/30249621/66662452-7baad000-ec0e-11e9-974a-f94680cb4195.png">
When using the paid version the event date and time are displayed. Screenshot below shows the lite version on the right.
<img width="767" alt="Screen Shot 2019-10-11 at 9 54 34 AM" src="https://user-images.githubusercontent.com/30249621/66662533-a137d980-ec0e-11e9-83f3-bdbf0062837d.png">

**Expected behavior:**
When viewing the details of an event the date and time are displayed.

First reported by a customer: https://secure.helpscout.net/conversation/978382551/134070?folderId=1909447
<img width="874" alt="Screen Shot 2019-10-11 at 10 05 52 AM" src="https://user-images.githubusercontent.com/30249621/66662600-ba408a80-ec0e-11e9-8948-eead8a9617a4.png">

**Comment by JJJ** [comment]
Fixed upstream in the Standard (private) repository, and will be in the 2.0.9 release for Lite also.
