### ISSUE TITLE
Add promo section to admin screen

### ISSUE THREAD

**Issue by SDavisMedia** [sugarcalendar/lite#25]
Gonna add a sidebar section to the Settings page.

**Comment by SDavisMedia** [comment]
@JJJ I just had a quick thought. If you think there are other places in the plugin we should stick a promo, please let me know. I'm going to keep moving through the rest of the plugins for now, since I want to make sure all of them have just the basics (Settings promo). But if I have time, I can come back through and add more. So any thoughts are welcome.

**Comment by JJJ** [comment]
I have a hunch we are on the same page, with wanting to find an elegant way to raw attention to this, without it being annoying to users.

One thing that Sugar Calendar has support for, is a notification bubble (ala Pending Comments) in the Settings submenu text.

I’d like to use that bubble here, and in conjunction with a user option, mark it as “read” after their first visit to the page.

I also think this is a big opportunity for us to be inventive. My only hard & fast rules are that we shouldn’t muck with site content or search results. Everything else is on the table. Ive always thought it would be neat to create a new tab next to Screen Options and Help for “Special Offers” and use some JavaScript to position and control it. Something like that would be modular and easy to plunk into other projects/properties.

**Comment by SDavisMedia** [comment]
@JJJ Got it. That's a little more than what I was thinking for this particular initiative, because time is a big factor. I was just talking about putting the same promo (maybe tweaked to page context) in any other spots using the logic that's already in place. I wouldn't have time to build any new implementations.

**Comment by JJJ** [comment]
Oh yeah; I get that totally. There really aren’t any other different screens that seem appropriate IMO. _Possibly_ inside a Metabox on the Add New Event page, but that’s encroaching into site creation. I’ve seen it done, just unsure if it converts enough to be as invasive as it is.

**Comment by SDavisMedia** [comment]
@JJJ I was looking there too. I was thinking text only. No CSS or images at all. Just a short blurb and a single link to the site pricing page.

Feel free to think on it for a day or so. I'm finishing up WPSP and then gonna hit EDD. So I'll be back around here by the weekend. Hoping to have all of these ready for final review when everyone logs on Monday morning.
